### ISSUE TITLE
Final Project TODO List

### ISSUE THREAD

**Issue by MKLepium** [MKLepium/DD2356-Assignments#1]
- [x] describe the selected application and the evaluated problems (E) 
- [x] compile and run the application on Dardel on multiple compute nodes (E)
- [ ] use IPM and pert profiling tools to profile the application on Dardel (E)
- [ ] design the profiling methodology on Dardel (D)
- [ ] describe the obtained profiling results (D)
- [ ] describe the communication patterns (C)
- [ ] analyze the profiling results and the scalability (C)
- [ ] Identify potential performance bottlenecks (B)
- [ ] Propose one or two optimizations to overcome the identified bottlenecks (B) 
- [ ] Compare the profiling results from two MPI implementations (A)
- [ ] The code repository is accessible if code modification is described in the report. (E)
- [ ] the presentation has good time management (all slides are covered within 15 min, leaving 5min for Q&A) (E)
- [ ] the presentation describes the project's goals and methodology (E)
- [ ] The presentation includes concluding thoughts that describe the results of the project. (D)
- [ ] The presentation contains suitable visual aids such as slides, figures, or images. (C)
- [ ] The presentation is clear. (B)
- [ ] The presentation answers questions in Q&A session clearly. (A)

**Comment by pierrelefevre** [comment]
- [ ] A summary of each group member's contributions
- [ ] Introduction. Provide some background on the selected application and input problem
- [ ] Methodology. Explain the metrics you evaluated and how they are derived from profiling results.
- [ ] Experimental Setup. Describe the platform (both software and hardware) you used for your project and the tools you used.
- [ ] Results. Present the performance/profiling results.
- [ ] Analysis. Discuss the performance results critically and if any optimizations can be identified from the results (you don’t have to implement them).
- [ ] Conclusion. Describe the main insights, challenges, and limitations of your work and future works if you are given more time.
- [ ] References. Provide a list of articles and books you consulted for preparing the project.
